### ISSUE TITLE
reply to/quoted messages appear in a weird way

### ISSUE THREAD

**Issue by roughnecks** [26000/irchuu#10]
Hello.

Is it normal behavior for irchuu to post quoted TG messages as:

`14:29   gonzo_nzo | <@r0ughn3cks> melmothX, test
`
without quoting the message one is replying to? This is me quoting melmothX and saying "test"; gonzo_zo is the bot.

Here's the TG message: https://i.imgur.com/psUJUuG.png

**Comment by 26000** [comment]
It's intended behavior. In IRC, you usually don't quote the message you're replying to (due to interface limitations, among other things). So, I decided that the bridge should be doing the same (and it's hard to implement nicely anyway).
