### ISSUE TITLE
support for /names

### ISSUE THREAD

**Issue by roughnecks** [26000/irchuu#11]
Hello,

is there any chance of getting the equivalent of IRC command "/names" in Telegram, to know who is connected on IRC?

Thanks

**Comment by unnamsa** [comment]
we use on our IRC telegram channel, @IRC_Chelyabinsk, admin name as nick. It's writed as grey colour on right side. but only 50 admins limit on telegram ( Need bot with who, whois, userinfo irc commands )

**Comment by 26000** [comment]
There's no way (besides doing complicated stuff with a database) to see the list of Telegram chat members. So, for functionality to be more or less symmetric on both sides, I only implemented the `ops` command in both Telegram and IRC.

@unnamsa, I'm not sure what do you mean by "who, whois, userinfo irc commands". The ability to see the IRC user info from Telegram? I don't think a "who" command would make sense, and I don't like the idea of exposing IRC users' hostmasks for privacy reasons.

**Comment by unnamsa** [comment]
> ability to see the IRC user info from Telegram

Yeah. Only nickname as minimum. In Telegramm, many of our people can’t change their main nickname to the former nickname of the channel’s IRC, as before it was too crazy to shine with everyone now. But to know who writes to you and how his nickname used to be, it is necessary - now we have decided this only for 50 people appointed by administrators through their "post" in a telegram.

**Comment by unnamsa** [comment]
It's feature for users in Telegram who want see users on Telegram. ) private lists of nicks, may be

**Comment by 26000** [comment]
Wait, I don't understand it at all. How being able to see IRC info (hostmask and realname?) would help it?

Do I understand correctly that you have an IRC channel, some users migrated to Telegram and are unable to use their old IRC nicknames? Is what you're asking for a map between old IRC nicknames and new Telegram usernames? If so, I don't think I'll implement it, your use case is too specific.

**Comment by unnamsa** [comment]
Yes, may be it so specific. It don't need to connect with IRC, userinfo maybe saved in pvt bot userlist only.. OK
