### ISSUE TITLE
Error, disconnect: EOF - what does it mean?

### ISSUE THREAD

**Issue by SLKTH** [26000/irchuu#12]
Getting this error after 1 minute.

```
IRC 2019/09/15 12:31:08 Connected to irc.server.de :6667 (82.73.134.248:6667)
IRC 2019/09/15 12:31:29 Error, disconnected: EOF
```

I have a server password set up. Password should be good.  Anyone know what's up?

**Comment by 26000** [comment]
It's an error from the IRC library I use. I'm not completely sure, but judging by the code, it probably happens upon receiving a string that doesn't end in '\n' from the server. Which should never happen, according to [RFC 1459](https://tools.ietf.org/html/rfc1459#section-2.3). So, most probably, it's the server you're connecting to misbehaving.
