### ISSUE TITLE
Delay before joining IRC channel(s)

### ISSUE THREAD

**Issue by roughnecks** [26000/irchuu#16]
Hello,

would it be possible to add a delay (a few seconds) before joining a channel on IRC?
I'm asking because e.g. in freenode I'm using a cloak but irchuu joins before that's applied (soon after auth) and my public IP shows up in join message.

Thanks

**Comment by 26000** [comment]
Done!

**Comment by roughnecks** [comment]
Thanks :)

**Comment by roughnecks** [comment]
Hey, I just upgraded my bot with the following command:

go get github.com/26000/irchuu/cmd/irchuu

Then I added the config option for delay and set it to 10 seconds but it looks like my bot is joining very fast, like it used to.

Anything I should check? Thanks

**Comment by 26000** [comment]
I thought about releasing a new version to make it easier, but decided it's too small of a change :grimacing:

The option is `joindelay = <number of seconds>` in the IRC section (but as I understand you've already found it out? Sorry, I should've explained it in the previous message either way). It's possible that your system isn't using Go modules, then you could try `go get -u github.com/26000/irchuu/cmd/irchuu` to force update the package.

**Comment by roughnecks** [comment]
Yeah, I added that option and:

```
roughnecks@CUSPIDE:~/.config$ go version
go version go1.13.7 linux/amd64
```

**Comment by roughnecks** [comment]
```
roughnecks@CUSPIDE:~$ ./go/bin/irchuu
IRChuu! v1.0.0 (https://github.com/26000/irchuu)
2020/02/15 18:26:58 Using configuration file: /home/roughnecks/.config/irchuu.conf
2020/02/15 18:26:58 Using data directory: /home/roughnecks/.local/share/irchuu
2020/02/15 18:26:58 Using the latest version of IRChuu.
 TG 2020/02/15 18:26:58 Authorized on account <cut>
IRC 2020/02/15 18:26:59 Connected to chat.freenode.net:7000 (162.213.39.42:7000)
IRC 2020/02/15 18:26:59 Notice from : *** Looking up your hostname...
IRC 2020/02/15 18:26:59 Notice from : *** Checking Ident
IRC 2020/02/15 18:26:59 Notice from : *** Couldn't look up your hostname
IRC 2020/02/15 18:26:59 Notice from : *** No Ident response
IRC 2020/02/15 18:26:59 Trying to authenticate via NickServ
IRC 2020/02/15 18:26:59 Notice from NickServ: This nickname is registered. Please choose a different nickname, or identify via /msg NickServ identify <password>.
IRC 2020/02/15 18:27:00 Notice from freenode-connect: Welcome to freenode. To protect the network all new connections will be scanned for vulnerabilities. This will not harm your computer, and vulnerable hosts will be notified.
IRC 2020/02/15 18:27:00 CTCP VERSION from freenode-connect
IRC 2020/02/15 18:27:05 Joined <cut>
IRC 2020/02/15 18:27:14 Notice from NickServ: You are now identified for <cut>.
```

**Comment by 26000** [comment]
Go can still use the old dependency management system even if you have the newest version, I guess I should look into it as I don't know the details. Also you could try `go get -u github.com/26000/irchuu/...`.

If that doesn't help (it should say "Waiting \<x>s before joining the channel...", didn't work if it doesn't), try navigating to `$GOROOT/pkg/mod/github.com/irchuu@something/irc/irc.go` and see what's on line 385 there (should be [this](https://github.com/26000/irchuu/blob/master/irc/irc.go#L385)). If that file and directories below don't exist, then it should be at `$GOROOT/src/github.com/26000/irchuu/irc/irc.go` (not using modules).

**Comment by roughnecks** [comment]
Alright, I did what you told me:

`go get -u github.com/26000/irchuu/cmd/irchuu`

And it worked. Now I can see the "waiting" message :)
Thank you so much, keep it up!

**Comment by 26000** [comment]
Yay :)

Perhaps I should read more about how Go chooses whether to use modules or not and update the upgrading instructions accordingly...
