### ISSUE TITLE
Remove webserver index

### ISSUE THREAD

**Issue by roughnecks** [26000/irchuu#23]
Hello,

would it be possible to remove webserver index? (I mean the "storage = server" option)
It's not so cool if everyone can access private group content.

Thanks

**Comment by 26000** [comment]
You can create an empty file called `index.html` in the file server directory (`~/.local/share/irchuu/` by default). That should disable the index. Hope this solution works for you; if it doesn't, please tell.

**Comment by roughnecks** [comment]
It's working, thanks!
