### ISSUE TITLE
ServerName or InsecureSkipVerify must be specified in the tls.Config

### ISSUE THREAD

**Issue by roughnecks** [26000/irchuu#26]
Hello,

my friend upgraded his server and I (responsible for the bot) recompiled it, same conf.
Now when I start it I get a lot of these messages :

IRC 2021/09/17 12:47:14 Connected to irc.libera.chat:6697
IRC 2021/09/17 12:47:14 Error, disconnected: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config

and we have no idea what tls.Config is.
He upgraded from Debian Buster to Bullseye and go from 1.11 to 1.15

Can you help?
Thanks

**Comment by 26000** [comment]
I couldn't reproduce the issue, but pushed a potential fix in
052cee4efacdf31954c58f7708d61b7f9c616ead. Please test the new version
and report back; if it works, I'll publish a bugfix release.

**Comment by roughnecks** [comment]
It works now, I just updated as soon as I saw the fix.

Thanks

**Comment by 26000** [comment]
Oh, good, thanks for the update. I published a new release.
