### ISSUE TITLE
Could not upload media [...]: invalid character 'U' looking for beginning of value

### ISSUE THREAD

**Issue by eikoninaru** [26000/irchuu#28]
Hi there!

Set up pomf with `https://p.fuwafuwa.moe` server but couldn't upload media, got this error `Could not upload media CgACAgQAAx0CT9xPrwACqtZjn78kun2VG2KZHS_5bPoMOw95XwACGQMAAqXQBVNTH2cSDvQgXCwE: invalid character 'U' looking for beginning of value`

Any help, please

**Comment by 26000** [comment]
Hello! Sorry for the late response. Unfortunately https://p.fuwafuwa.moe <https://p.fuwafuwa.moe/> seems to have disabled uploads, so I can’t test it. Not sure if they were disabled at the time you created this issue or not.

**Comment by eikoninaru** [comment]
maybe you know other resources that can be used to upload media?

**Comment by 26000** [comment]
I haven't used public services like that in a while, so not aware of what currently exists. There used to be a helpful Google Doc with a list of POMF clones, but it's gone now.
