### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tigercosmos** [26000/irchuu#4]
Could this also send message from telegram to IRC?
I only can receive from IRC after I setup the bot and run the program.

**Comment by 26000** [comment]
Hey! Yep, of course. Have you set group privacy for your Telegram Bot (in botfather)? When you set it, you need to re-add your bot to your group.

**Comment by tigercosmos** [comment]
it works! thanks :)

**Comment by tigercosmos** [comment]
@26000 How to set filter for messages from IRC? or where to modify the code?

**Comment by 26000** [comment]
There's now way to do this through configuration as now, how would you like it to be implemented? Block messages if they fit a regexp?

[Here](https://github.com/26000/irchuu/blob/master/irc/irc.go#L257) the PRIVMSGs are relayed, you can add a filter there. Also [here](https://github.com/26000/irchuu/blob/master/irc/irc.go#L80) NOTICEs are relayed. You can search for `IRCh <-` in code to find other places, but you probably don't need to.

**Comment by 26000** [comment]
If you want it to be implemented in upstream IRChuu, then please open a new issue!

**Comment by tigercosmos** [comment]
In fact, I want to filter messages like:
- allizom has joined.
- ccoroiu is now known as ccoroiu|sheriffduty.
- KiChjang has quit: Connection closed.

These are noisy.

**Comment by tigercosmos** [comment]
Seems there is a option in config to do this :)

**Comment by tigercosmos** [comment]
But seems we cannot filter message like "Liu An Chi added Shing Lyu" from telegram to IRC?

**Comment by 26000** [comment]
>Seems there is a option in config to do this :)

Ah, yep ^^" I thought you were talking about filtering bot messages or something like that.

>But seems we cannot filter message like "Liu An Chi added Shing Lyu" from telegram to IRC?

Without editing the code, no, for now.
