### ISSUE TITLE
Sending message failed: Bad Request: chat not found

### ISSUE THREAD

**Issue by roughnecks** [26000/irchuu#6]
Hello

I can't for the life of me understand how to tell the bot how to join my TG group.
I'm not sure if the ID is right but it should be.

As soon as I add the bot to my group and launch it, it spits out this in TG:

I'm not configured to work in this group (group id: -324.....).

And then it exits.

While on the terminal I read what I wrote in the subject: "chat not found".

Any help please?
Thanks

**Comment by roughnecks** [comment]
There's also this random message in terminal:

TG 2019/08/19 00:14:38 Sending message failed: Forbidden: bot can't initiate conversation with a user

**Comment by roughnecks** [comment]
Nevermind, I think I needed to write my group ID with a leading "-".

**Comment by 26000** [comment]
Sorry, I was busy, so couldn't answer in time. Glad that you've figured it out!
