### ISSUE TITLE
Bots and ignore

### ISSUE THREAD

**Issue by roughnecks** [26000/irchuu#7]
Hello.

Does irchuu ignores other Telegram bots?
Any (future) way to have personalized ignore list (both IRC and Telegram)?

**Comment by 26000** [comment]
Telegram [doesn't](https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots) allow bots to see each other. So, unfortunately, relaying bot messages from Telegram to IRC is impossible.

So, I don't see a usecase for a Telegram ignore list. As for an ignore list on the IRC side, that's a good idea, I'll open an issue for that task specifically.

**Comment by roughnecks** [comment]
Thanks, I didn't know about that.
