### ISSUE TITLE
Sending message failed: Forbidden: bot can't initiate conversation with a user

### ISSUE THREAD

**Issue by spikespaz** [26000/irchuu#9]
Everything is default and I'm using SASL for authentication. All I did was follow instructions on the readme.

**Comment by 26000** [comment]
This isn't a fatal error, it just means that the bot attempted to private message a user that didn't message them first. However, it's weird that you're getting these, as the bot should never attempt to message the user first...

Does it work otherwise, besides generating these errors?

**Comment by spikespaz** [comment]
No, it doesn't work. I will try again tomorrow.

**Comment by spikespaz** [comment]
Every time a message is sent in the IRC channel I get the error in the title, `Sending message failed: Forbidden: bot can't initiate conversation with a user`

**Comment by 26000** [comment]
Oh, I just realized that it can happen when you specify a user's ID instead of the group ID. In config, do you have a minus sign before the Telegram group ID? I don't remember what it's like for usual groups, but IIRC, supergroups' IDs always start with -100.

**Comment by spikespaz** [comment]
I created a telegram group and added the bot to it, ran the bot, it gave me the group ID and I copy pasted that into the config. It is a negative integer.

**Comment by 26000** [comment]
Oh, I guess I know the reason (missed it somehow). The bot leaves from the group after printing its ID. So you need to re-add it. I changed this behavior in v0.10.1, this is no longer necessary for new setups.

Sorry for such a long delay and not being clear enough in README.
